AWSTemplateFormatVersion: "2010-09-09"
Description: "S1 ingest V2 layer for Vectora Inbox: Lambda function vectora-inbox-ingest-v2 in eu-west-3."

Parameters:
  ProjectName:
    Type: String
    Default: "vectora-inbox"
    Description: "Nom du projet (préfixe des fonctions Lambda)."

  Env:
    Type: String
    Default: "dev"
    AllowedValues:
      - dev
      - stage
      - prod
    Description: "Environnement cible (dev, stage, prod)."

  ConfigBucketName:
    Type: String
    Description: "Nom du bucket S3 de configuration (ex: vectora-inbox-config-dev)."

  DataBucketName:
    Type: String
    Description: "Nom du bucket S3 de données (ex: vectora-inbox-data-dev)."

  IngestV2RoleArn:
    Type: String
    Description: "ARN du rôle IAM pour la Lambda d'ingestion V2 (depuis S0-iam)."

  IngestV2CodeBucket:
    Type: String
    Description: "Nom du bucket S3 contenant le code de la Lambda ingest-v2."

  IngestV2CodeKey:
    Type: String
    Default: "lambda/ingest-v2/latest.zip"
    Description: "Clé S3 du package de code pour la Lambda ingest-v2."

  LambdaRuntime:
    Type: String
    Default: "python3.12"
    AllowedValues:
      - python3.11
      - python3.12
    Description: "Runtime Python pour les fonctions Lambda."

  LambdaTimeout:
    Type: Number
    Default: 900
    MinValue: 60
    MaxValue: 900
    Description: "Timeout de la fonction Lambda en secondes (15 minutes max)."

  LambdaMemorySize:
    Type: Number
    Default: 512
    MinValue: 128
    MaxValue: 10240
    Description: "Mémoire allouée à la fonction Lambda en Mo."

  LogRetentionDays:
    Type: Number
    Default: 7
    AllowedValues:
      - 1
      - 3
      - 5
      - 7
      - 14
      - 30
      - 60
      - 90
      - 120
      - 150
      - 180
      - 365
    Description: "Durée de rétention des logs CloudWatch en jours."

Resources:
  # CloudWatch Log Group pour la Lambda ingest-v2
  IngestV2LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ProjectName}-ingest-v2-${Env}"
      RetentionInDays: !Ref LogRetentionDays

  # Fonction Lambda : ingest-v2
  IngestV2Function:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-ingest-v2-${Env}"
      Runtime: !Ref LambdaRuntime
      Handler: "handler.lambda_handler"
      Role: !Ref IngestV2RoleArn
      Code:
        S3Bucket: !Ref IngestV2CodeBucket
        S3Key: !Ref IngestV2CodeKey
      Timeout: !Ref LambdaTimeout
      MemorySize: !Ref LambdaMemorySize
      Environment:
        Variables:
          ENV: !Ref Env
          PROJECT_NAME: !Ref ProjectName
          CONFIG_BUCKET: !Ref ConfigBucketName
          DATA_BUCKET: !Ref DataBucketName
          LOG_LEVEL: "INFO"
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Env
          Value: !Ref Env
        - Key: FunctionType
          Value: "ingest-v2"

Outputs:
  IngestV2FunctionName:
    Description: "Nom de la fonction Lambda d'ingestion V2."
    Value: !Ref IngestV2Function

  IngestV2FunctionArn:
    Description: "ARN de la fonction Lambda d'ingestion V2."
    Value: !GetAtt IngestV2Function.Arn

  IngestV2LogGroupName:
    Description: "Nom du groupe de logs CloudWatch pour la Lambda ingest-v2."
    Value: !Ref IngestV2LogGroup