AWSTemplateFormatVersion: "2010-09-09"
Description: "S1 runtime layer for Vectora Inbox: Lambda functions (ingest-normalize and engine) in eu-west-3."

Parameters:
  ProjectName:
    Type: String
    Default: "vectora-inbox"
    Description: "Nom du projet (préfixe des fonctions Lambda)."

  Env:
    Type: String
    Default: "dev"
    AllowedValues:
      - dev
      - stage
      - prod
    Description: "Environnement cible (dev, stage, prod)."

  ConfigBucketName:
    Type: String
    Description: "Nom du bucket S3 de configuration (ex: vectora-inbox-config-dev)."

  DataBucketName:
    Type: String
    Description: "Nom du bucket S3 de données (ex: vectora-inbox-data-dev)."

  NewslettersBucketName:
    Type: String
    Description: "Nom du bucket S3 de newsletters (ex: vectora-inbox-newsletters-dev)."

  IngestNormalizeRoleArn:
    Type: String
    Description: "ARN du rôle IAM pour la Lambda d'ingestion + normalisation (depuis S0-iam)."

  EngineRoleArn:
    Type: String
    Description: "ARN du rôle IAM pour la Lambda engine (depuis S0-iam)."

  IngestNormalizeCodeBucket:
    Type: String
    Description: "Nom du bucket S3 contenant le code de la Lambda ingest-normalize."

  IngestNormalizeCodeKey:
    Type: String
    Default: "lambda/ingest-normalize/latest.zip"
    Description: "Clé S3 du package de code pour la Lambda ingest-normalize."

  EngineCodeBucket:
    Type: String
    Description: "Nom du bucket S3 contenant le code de la Lambda engine."

  EngineCodeKey:
    Type: String
    Default: "lambda/engine/latest.zip"
    Description: "Clé S3 du package de code pour la Lambda engine."

  PubmedApiKeyParamPath:
    Type: String
    Default: "/rag-lai/dev/pubmed/api-key"
    Description: "Chemin du paramètre SSM pour la clé API PubMed."

  BedrockModelId:
    Type: String
    Default: "eu.anthropic.claude-sonnet-4-5-20250929-v1:0"
    Description: "Identifiant du profil d'inférence Bedrock cross-region EU pour Claude Sonnet 4.5 - Amazon Bedrock Edition. Les modèles Anthropic récents nécessitent un inference profile. Le profil EU cross-region route les requêtes vers eu-north-1, eu-west-3, eu-south-1, eu-south-2, eu-west-1, eu-central-1."

  LambdaRuntime:
    Type: String
    Default: "python3.12"
    AllowedValues:
      - python3.11
      - python3.12
    Description: "Runtime Python pour les fonctions Lambda."

  LambdaTimeout:
    Type: Number
    Default: 300
    MinValue: 60
    MaxValue: 900
    Description: "Timeout des fonctions Lambda en secondes (5 minutes par défaut)."

  LambdaMemorySize:
    Type: Number
    Default: 512
    MinValue: 128
    MaxValue: 10240
    Description: "Mémoire allouée aux fonctions Lambda en Mo."

  LogRetentionDays:
    Type: Number
    Default: 7
    AllowedValues:
      - 1
      - 3
      - 5
      - 7
      - 14
      - 30
      - 60
      - 90
      - 120
      - 150
      - 180
      - 365
    Description: "Durée de rétention des logs CloudWatch en jours."

Conditions:
  # Condition pour appliquer des configurations spécifiques à l'environnement DEV
  IsDevEnvironment: !Equals [!Ref Env, "dev"]

Resources:
  # CloudWatch Log Group pour la Lambda ingest-normalize
  IngestNormalizeLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ProjectName}-ingest-normalize-${Env}"
      RetentionInDays: !Ref LogRetentionDays

  # Fonction Lambda : ingest-normalize
  IngestNormalizeFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-ingest-normalize-${Env}"
      Runtime: !Ref LambdaRuntime
      Handler: "handler.lambda_handler"
      Role: !Ref IngestNormalizeRoleArn
      Code:
        S3Bucket: !Ref IngestNormalizeCodeBucket
        S3Key: !Ref IngestNormalizeCodeKey
      Timeout: !Ref LambdaTimeout
      MemorySize: !Ref LambdaMemorySize
      Environment:
        Variables:
          ENV: !Ref Env
          PROJECT_NAME: !Ref ProjectName
          CONFIG_BUCKET: !Ref ConfigBucketName
          DATA_BUCKET: !Ref DataBucketName
          BEDROCK_MODEL_ID: !Ref BedrockModelId
          PUBMED_API_KEY_PARAM: !Ref PubmedApiKeyParamPath
          LOG_LEVEL: "INFO"
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Env
          Value: !Ref Env
        - Key: FunctionType
          Value: "ingest-normalize"

  # CloudWatch Log Group pour la Lambda engine
  EngineLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${ProjectName}-engine-${Env}"
      RetentionInDays: !Ref LogRetentionDays

  # Fonction Lambda : engine
  EngineFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-engine-${Env}"
      Runtime: !Ref LambdaRuntime
      Handler: "handler.lambda_handler"
      Role: !Ref EngineRoleArn
      Code:
        S3Bucket: !Ref EngineCodeBucket
        S3Key: !Ref EngineCodeKey
      Timeout: !Ref LambdaTimeout
      MemorySize: !Ref LambdaMemorySize
      Environment:
        Variables:
          ENV: !Ref Env
          PROJECT_NAME: !Ref ProjectName
          CONFIG_BUCKET: !Ref ConfigBucketName
          DATA_BUCKET: !Ref DataBucketName
          NEWSLETTERS_BUCKET: !Ref NewslettersBucketName
          BEDROCK_MODEL_ID: !Ref BedrockModelId
          LOG_LEVEL: "INFO"
      Tags:
        - Key: Project
          Value: !Ref ProjectName
        - Key: Env
          Value: !Ref Env
        - Key: FunctionType
          Value: "engine"

Outputs:
  IngestNormalizeFunctionName:
    Description: "Nom de la fonction Lambda d'ingestion + normalisation."
    Value: !Ref IngestNormalizeFunction

  IngestNormalizeFunctionArn:
    Description: "ARN de la fonction Lambda d'ingestion + normalisation."
    Value: !GetAtt IngestNormalizeFunction.Arn

  EngineFunctionName:
    Description: "Nom de la fonction Lambda engine."
    Value: !Ref EngineFunction

  EngineFunctionArn:
    Description: "ARN de la fonction Lambda engine."
    Value: !GetAtt EngineFunction.Arn

  IngestNormalizeLogGroupName:
    Description: "Nom du groupe de logs CloudWatch pour la Lambda ingest-normalize."
    Value: !Ref IngestNormalizeLogGroup

  EngineLogGroupName:
    Description: "Nom du groupe de logs CloudWatch pour la Lambda engine."
    Value: !Ref EngineLogGroup
