# ============================================================================
# LAI INTELLIGENCE WEEKLY - CLIENT CONFIG v12 (CORRECTIF MATCHING)
# ============================================================================
#
# Configuration client v12 pour "LAI Intelligence Weekly" - Correctif Domain Definition
# Newsletter hebdomadaire centrée sur les technologies LAI (Long-Acting Injectables)
#
# OBJECTIF v12 : Corriger 0% matching via domain_definitions.yaml
# Base : lai_weekly_v11.yaml (copie identique)
#
# ============================================================================

# ============================================================================
# PROFIL CLIENT
# ============================================================================

client_profile:
  name: "LAI Intelligence Weekly v12 (Test Domain Definition Fix)"
  client_id: "lai_weekly_v12"
  active: true
  language: "en"
  frequency: "weekly"
  tone: "executive"
  voice: "concise"
  target_audience: "executives"

# ============================================================================
# CONFIGURATION DU PIPELINE
# ============================================================================

pipeline:
  newsletter_mode: "latest_run_only"
  default_period_days: 30
  notes: "Version v12 - Test après ajout domain_definitions.yaml"

# ============================================================================
# CONFIGURATION BEDROCK (APPROCHE B - PROMPTS PRÉ-CONSTRUITS)
# ============================================================================

bedrock_config:
  normalization_prompt: "generic_normalization"  # Appel 1: Normalisation générique
  domain_scoring_prompt: "lai_domain_scoring"  # Appel 2: Domain scoring LAI
  editorial_prompt: "lai_editorial"
  enable_domain_scoring: true  # Architecture v2 validée

# ============================================================================
# DOMAINES DE VEILLE
# ============================================================================

watch_domains:
  - id: "tech_lai_ecosystem"
    type: "technology"
    priority: "high"
    
    technology_scope: "lai_keywords"
    company_scope: "lai_companies_global"
    molecule_scope: "lai_molecules_global"
    trademark_scope: "lai_trademarks_global"
    
    technology_profile: "technology_complex"
    matching_profile: "balanced"
    
    enabled: true
    notes: "Domaine unique v12 - test après ajout domain_definitions.yaml"

# ============================================================================
# CONFIGURATION DES SOURCES
# ============================================================================

source_config:
  source_bouquets_enabled:
    - "lai_corporate_mvp"
    - "lai_press_mvp"
  
  sources_extra_enabled: []
  bouquet_ingestion_overrides: {}
  
  content_filters:
    min_word_count: 50
    exclude_patterns:
      - "Download attachment"
      - "View attachment"
      - "Read more"

# ============================================================================
# CONFIGURATION DU MATCHING V2
# ============================================================================

matching_config:
  min_domain_score: 0.25
  min_confidence_level: "low"
  
  domain_type_thresholds:
    technology: 0.30
    
  enable_fallback_mode: true
  fallback_min_score: 0.15
  fallback_max_domains: 1
  fallback_company_scopes:
    - "lai_companies_global"
    
  max_domains_per_item: 1
  require_high_confidence_for_multiple: false
  
  enable_diagnostic_mode: true
  store_rejection_reasons: true
  
  default_matching_mode: "balanced"
  
  domain_type_overrides:
    technology:
      require_entity_signals: true
      min_technology_signals: 2
  
  trademark_privileges:
    enabled: true
    auto_match_threshold: 0.8
    boost_factor: 2.5
    ingestion_priority: true
    matching_priority: true

# ============================================================================
# CONFIGURATION DU SCORING
# ============================================================================

scoring_config:
  event_type_weight_overrides:
    partnership: 8
    clinical_update: 6
    regulatory: 7
    scientific_publication: 4
  
  client_specific_bonuses:
    pure_player_companies:
      scope: "lai_companies_mvp_core"
      bonus: 5.0
      description: "Pure players LAI - signal très fort"
    
    trademark_mentions:
      scope: "lai_trademarks_global"
      bonus: 4.0
      description: "Mentions de marques LAI - signal privilégié"
    
    key_molecules:
      scope: "lai_molecules_global"
      bonus: 2.5
      description: "Molécules LAI d'intérêt"
    
    hybrid_companies:
      scope: "lai_companies_hybrid"
      bonus: 1.5
      description: "Big pharma avec activité LAI"
  
  selection_overrides:
    min_score: 12
    min_items_per_section: 1
    max_items_total: 15

# ============================================================================
# STRUCTURE DE LA NEWSLETTER
# ============================================================================

newsletter_selection:
  max_items_total: 20
  min_score_threshold: 0
  
  critical_event_types:
    - "regulatory_approval"
    - "nda_submission" 
    - "pivotal_trial_result"
    - "partnership"
    - "clinical_update"
    - "regulatory"
    - "corporate_move"
  
  trimming_policy:
    preserve_critical_events: true
    min_items_per_section: 1
    max_section_dominance: 0.6
    prefer_recent_items: true
  
  deduplication:
    enabled: true
    similarity_threshold: 0.75
    prefer_critical_events: true
    prefer_higher_score: true
    company_based_dedup: true

newsletter_layout:
  distribution_strategy: "specialized_with_fallback"
  
  sections:
    - id: "regulatory_updates"
      title: "Regulatory Updates"
      source_domains:
        - "tech_lai_ecosystem"
      max_items: 6
      filter_event_types:
        - "regulatory"
      sort_by: "score_desc"
      priority: 1
      
    - id: "partnerships_deals"
      title: "Partnerships & Deals"
      source_domains:
        - "tech_lai_ecosystem"
      max_items: 4
      filter_event_types:
        - "partnership"
        - "corporate_move"
      sort_by: "date_desc"
      priority: 2
      
    - id: "clinical_updates"
      title: "Clinical Updates"
      source_domains:
        - "tech_lai_ecosystem"
      max_items: 5
      filter_event_types:
        - "clinical_update"
      sort_by: "date_desc"
      priority: 3
      
    - id: "others"
      title: "Other Signals"
      source_domains:
        - "tech_lai_ecosystem"
      max_items: 8
      filter_event_types:
        - "*"
      sort_by: "score_desc"
      priority: 999
      notes: "Filet de sécurité - aucun item perdu"

# ============================================================================
# CONFIGURATION DE LIVRAISON
# ============================================================================

newsletter_delivery:
  format: "markdown"
  include_tldr: true
  include_intro: true
  include_metrics: true
  delivery_method: "s3"
  notification_email: "lai-weekly-v12@vectora.com"
  
  metrics_config:
    include_source_breakdown: true
    include_domain_breakdown: true
    include_trend_analysis: false

# ============================================================================
# MÉTADONNÉES
# ============================================================================

metadata:
  template_version: "12.0.0"
  created_date: "2026-02-03"
  last_modified: "2026-02-03"
  created_by: "Correctif Matching - Domain Definition Fix"
  
  min_runtime_version: "2.0.0"
  canonical_version: "2.1"
  
  vertical: "LAI"
  target_market: "Long-Acting Injectables"
  coverage_scope: "Global"
  
  creation_notes: |
    Création lai_weekly_v12.yaml depuis lai_weekly_v11.yaml
    
    OBJECTIF v12 (Correctif Matching):
    🎯 Corriger 0% matching via lai_domain_definition.yaml
    🎯 Valider architecture 2 appels Bedrock
    🎯 Baseline pour amélioration continue
    
    MODIFICATIONS v11 → v12:
    ✅ client_id: "lai_weekly_v11" → "lai_weekly_v12"
    ✅ client_profile.name: "v11 (Test Prompts Cleanup)" → "v12 (Test Domain Definition Fix)"
    ✅ notification_email: "lai-weekly-v12@vectora.com"
    ✅ template_version: "11.0.0" → "12.0.0"
    ✅ canonical_version: "2.0" → "2.1"
    ✅ created_by: "Correctif Matching - Domain Definition Fix"
    ✅ Ajout domain_definitions.yaml (CANONICAL_VERSION 2.1)
    
    CONFIG IDENTIQUE À v11:
    ✅ bedrock_config.domain_scoring_prompt: "lai_domain_scoring"
    ✅ bedrock_config.enable_domain_scoring: true
    ✅ pipeline.default_period_days: 30
    ✅ newsletter_selection.max_items_total: 20
    ✅ Tous les autres paramètres identiques
    
    NOUVEAUTÉ v12:
    ✅ canonical/scopes/domain_definitions.yaml v1.0.0
       - Définition formelle du domaine LAI
       - Signaux forts/moyens/faibles
       - Règles de matching explicites
       - Scores de base par type d'événement
       - Boosts par type d'entité
    
    CONFORMITÉ GOUVERNANCE:
    ✅ Branche: fix/matching-domain-definition-v12
    ✅ VERSION incrémentée: CANONICAL_VERSION 2.0 → 2.1
    ✅ Commit AVANT sync S3
    
    ARCHITECTURE 2 APPELS BEDROCK:
    1. Normalisation générique (generic_normalization.yaml)
       - Extraction entités (companies, molecules, technologies, trademarks, indications)
       - Classification événement (partnership, regulatory, clinical_update, etc.)
       - Génération résumé
       - Extraction date + confidence
    
    2. Domain scoring (lai_domain_scoring.yaml)
       - Utilise domain_definitions.yaml pour matching
       - Détection signaux (strong/medium/weak)
       - Application matching rules
       - Calcul score 0-100
       - Génération reasoning
    
    PRÊT POUR TEST E2E AWS DEV

# ============================================================================
# FIN DE CONFIGURATION
# ============================================================================
