# ============================================================================
# LAI INTELLIGENCE WEEKLY - CLIENT CONFIG v4 (TECH FOCUS)
# ============================================================================
#
# Configuration client v4 pour "LAI Intelligence Weekly" - Version tech focus
# Newsletter hebdomadaire centrée sur les technologies LAI (Long-Acting Injectables)
#
# OBJECTIF v4 : Focus exclusif sur tech_lai_ecosystem (suppression regulatory_lai)
# Base : lai_weekly_v3.yaml avec un seul watch_domain
#
# ============================================================================

# ============================================================================
# PROFIL CLIENT
# ============================================================================

client_profile:
  name: "LAI Intelligence Weekly v4 (Tech Focus)"
  client_id: "lai_weekly_v4"
  active: true
  language: "en"
  frequency: "weekly"
  tone: "executive"
  voice: "concise"
  target_audience: "executives"

# ============================================================================
# CONFIGURATION DU PIPELINE
# ============================================================================

pipeline:
  default_period_days: 30
  notes: "Fenêtre étendue pour capturer les signaux LAI sur cycle long - Version v4 tech focus"

# ============================================================================
# DOMAINES DE VEILLE
# ============================================================================

watch_domains:
  # ---------------------------------------------------------------------------
  # DOMAINE UNIQUE : Écosystème LAI complet (technology focus)
  # ---------------------------------------------------------------------------
  - id: "tech_lai_ecosystem"
    type: "technology"
    priority: "high"
    
    # Scopes LAI (références canonical/scopes/)
    technology_scope: "lai_keywords"
    company_scope: "lai_companies_global"
    molecule_scope: "lai_molecules_global"
    trademark_scope: "lai_trademarks_global"
    
    # Profils
    technology_profile: "technology_complex"
    matching_profile: "balanced"
    
    enabled: true
    notes: "Domaine unique v4 - focus exclusif sur l'écosystème technologique LAI"

# ============================================================================
# CONFIGURATION DES SOURCES
# ============================================================================

source_config:
  source_bouquets_enabled:
    - "lai_corporate_mvp"
    - "lai_press_mvp"
  
  sources_extra_enabled: []
  bouquet_ingestion_overrides: {}

# ============================================================================
# CONFIGURATION DU MATCHING V2
# ============================================================================

matching_config:
  min_domain_score: 0.25
  min_confidence_level: "low"
  
  domain_type_thresholds:
    technology: 0.30
    
  enable_fallback_mode: true
  fallback_min_score: 0.15
  fallback_max_domains: 1
  fallback_company_scopes:
    - "lai_companies_global"
    
  max_domains_per_item: 1
  require_high_confidence_for_multiple: false
  
  enable_diagnostic_mode: true
  store_rejection_reasons: true
  
  default_matching_mode: "balanced"
  
  domain_type_overrides:
    technology:
      require_entity_signals: true
      min_technology_signals: 2
  
  trademark_privileges:
    enabled: true
    auto_match_threshold: 0.8
    boost_factor: 2.5
    ingestion_priority: true
    matching_priority: true

# ============================================================================
# CONFIGURATION DU SCORING
# ============================================================================

scoring_config:
  event_type_weight_overrides:
    partnership: 8
    clinical_update: 6
    regulatory: 7
    scientific_publication: 4
  
  client_specific_bonuses:
    pure_player_companies:
      scope: "lai_companies_mvp_core"
      bonus: 5.0
      description: "Pure players LAI - signal très fort"
    
    trademark_mentions:
      scope: "lai_trademarks_global"
      bonus: 4.0
      description: "Mentions de marques LAI - signal privilégié"
    
    key_molecules:
      scope: "lai_molecules_global"
      bonus: 2.5
      description: "Molécules LAI d'intérêt"
    
    hybrid_companies:
      scope: "lai_companies_hybrid"
      bonus: 1.5
      description: "Big pharma avec activité LAI"
  
  selection_overrides:
    min_score: 12
    min_items_per_section: 1
    max_items_total: 15

# ============================================================================
# STRUCTURE DE LA NEWSLETTER
# ============================================================================

newsletter_layout:
  sections:
    - id: "top_signals"
      title: "Top Signals – LAI Ecosystem"
      source_domains:
        - "tech_lai_ecosystem"
      max_items: 5
      sort_by: "score_desc"
    
    - id: "partnerships_deals"
      title: "Partnerships & Deals"
      source_domains:
        - "tech_lai_ecosystem"
      max_items: 5
      filter_event_types:
        - "partnership"
        - "corporate_move"
      sort_by: "date_desc"
    
    - id: "regulatory_updates"
      title: "Regulatory Updates"
      source_domains:
        - "tech_lai_ecosystem"
      max_items: 5
      filter_event_types:
        - "regulatory"
      sort_by: "score_desc"
    
    - id: "clinical_updates"
      title: "Clinical Updates"
      source_domains:
        - "tech_lai_ecosystem"
      max_items: 8
      filter_event_types:
        - "clinical_update"
      sort_by: "date_desc"

# ============================================================================
# CONFIGURATION DE LIVRAISON
# ============================================================================

newsletter_delivery:
  format: "markdown"
  include_tldr: true
  include_intro: true
  include_metrics: true
  delivery_method: "s3"
  notification_email: "lai-weekly-v4@vectora.com"
  
  metrics_config:
    include_source_breakdown: true
    include_domain_breakdown: true
    include_trend_analysis: false

# ============================================================================
# MÉTADONNÉES
# ============================================================================

metadata:
  template_version: "4.0.0"
  created_date: "2025-12-19"
  last_modified: "2025-12-19"
  created_by: "LAI Weekly v4 Tech Focus Creation"
  
  min_runtime_version: "2.0.0"
  canonical_version: "1.0.0"
  
  vertical: "LAI"
  target_market: "Long-Acting Injectables"
  coverage_scope: "Global"
  
  creation_notes: |
    Création lai_weekly_v4.yaml à partir de lai_weekly_v3.yaml :
    
    OBJECTIF v4 :
    🎯 Focus exclusif sur tech_lai_ecosystem
    🎯 Suppression du domaine regulatory_lai
    🎯 Simplification avec un seul watch_domain
    
    MODIFICATIONS v3 → v4 :
    ✅ client_id: "lai_weekly_v3" → "lai_weekly_v4"
    ✅ client_profile.name: "v3 (Test Bench)" → "v4 (Tech Focus)"
    ✅ watch_domains: Suppression de regulatory_lai
    ✅ watch_domains: Un seul domaine tech_lai_ecosystem
    ✅ max_domains_per_item: 2 → 1
    ✅ newsletter_layout: Toutes sections pointent vers tech_lai_ecosystem
    ✅ notification_email: "lai-weekly-v4@vectora.com"
    ✅ template_version: "3.0.0" → "4.0.0"
    
    PRÊT POUR TEST AVEC ARCHITECTURE BEDROCK-ONLY PURE

# ============================================================================
# FIN DE CONFIGURATION
# ============================================================================
